class Quiz {
    static questions = [
        {question: "Which AWS service is like a retro arcade cabinet - you pay per play?", options: ["A) EC2", "B) Lambda", "C) RDS", "D) S3"], correct: 1},
        {question: "Which service is like an old computer that runs 24/7 in your basement?", options: ["A) Lambda", "B) S3", "C) EC2", "D) RDS"], correct: 2},
        {question: "Which service is like a retro filing cabinet that never gets full?", options: ["A) EC2", "B) Lambda", "C) RDS", "D) S3"], correct: 3},
        {question: "Which service is like an old library card catalog system?", options: ["A) S3", "B) RDS", "C) Lambda", "D) EC2"], correct: 1},
        {question: "What does the λ symbol represent in AWS Lambda?", options: ["A) Greek letter Lambda", "B) Function symbol", "C) Both A and B", "D) AWS Logo"], correct: 2},
        {question: "Which service is like a retro jukebox - stores all your music?", options: ["A) EC2", "B) Lambda", "C) S3", "D) RDS"], correct: 2},
        {question: "AWS EC2 stands for?", options: ["A) Elastic Compute Cloud", "B) Easy Cloud Computing", "C) Electronic Computer Cloud", "D) Elastic Container Cloud"], correct: 0},
        {question: "Which service is serverless?", options: ["A) EC2", "B) RDS", "C) Lambda", "D) EBS"], correct: 2},
        {question: "S3 stands for?", options: ["A) Simple Storage Service", "B) Secure Storage System", "C) Super Storage Solution", "D) Standard Storage Service"], correct: 0},
        {question: "Which service is best for hosting a database?", options: ["A) S3", "B) Lambda", "C) EC2", "D) RDS"], correct: 3},
        {question: "Lambda functions have a maximum execution time of?", options: ["A) 5 minutes", "B) 15 minutes", "C) 30 minutes", "D) 1 hour"], correct: 1},
        {question: "Which service is like an old Polaroid camera - instant but temporary?", options: ["A) S3", "B) Lambda", "C) RDS", "D) EC2"], correct: 1},
        {question: "EC2 instances are like?", options: ["A) Virtual machines", "B) Storage buckets", "C) Functions", "D) Databases"], correct: 0},
        {question: "Which service automatically scales up and down?", options: ["A) RDS", "B) Lambda", "C) S3", "D) All of the above"], correct: 3},
        {question: "S3 bucket names must be?", options: ["A) Globally unique", "B) Regionally unique", "C) Account unique", "D) Not unique"], correct: 0},
        {question: "Which service is like a retro answering machine - responds to calls?", options: ["A) S3", "B) EC2", "C) Lambda", "D) RDS"], correct: 2},
        {question: "RDS supports which database engines?", options: ["A) MySQL only", "B) PostgreSQL only", "C) Multiple engines", "D) NoSQL only"], correct: 2},
        {question: "Lambda is triggered by?", options: ["A) Events", "B) Time schedules", "C) API calls", "D) All of the above"], correct: 3},
        {question: "Which service is like a retro TV antenna - receives signals?", options: ["A) Lambda", "B) S3", "C) EC2", "D) RDS"], correct: 0},
        {question: "EC2 pricing is based on?", options: ["A) Storage used", "B) Time running", "C) Data transfer", "D) All of the above"], correct: 3},
        {question: "S3 storage classes include?", options: ["A) Standard only", "B) Standard and IA", "C) Multiple classes", "D) Glacier only"], correct: 2},
        {question: "Which service is like a retro calculator - processes quickly?", options: ["A) S3", "B) Lambda", "C) RDS", "D) EC2"], correct: 1},
        {question: "RDS provides?", options: ["A) Managed databases", "B) Raw compute", "C) Object storage", "D) Functions"], correct: 0},
        {question: "Lambda supports which languages?", options: ["A) Python only", "B) Java only", "C) Multiple languages", "D) JavaScript only"], correct: 2},
        {question: "Which service is like a retro safe - stores valuables securely?", options: ["A) Lambda", "B) EC2", "C) S3", "D) RDS"], correct: 2},
        {question: "EC2 instances can be?", options: ["A) Started and stopped", "B) Only started", "C) Only stopped", "D) Never modified"], correct: 0},
        {question: "S3 provides?", options: ["A) 99.9% durability", "B) 99.99% durability", "C) 99.999999999% durability", "D) 100% durability"], correct: 2},
        {question: "Which service is like a retro radio - broadcasts to many?", options: ["A) RDS", "B) S3", "C) Lambda", "D) EC2"], correct: 1},
        {question: "Lambda pricing is based on?", options: ["A) Requests and duration", "B) Storage only", "C) Time running", "D) Data transfer only"], correct: 0},
        {question: "RDS backups are?", options: ["A) Manual only", "B) Automatic only", "C) Both manual and automatic", "D) Not supported"], correct: 2},
        {question: "Which service is like a retro typewriter - processes text?", options: ["A) S3", "B) EC2", "C) Lambda", "D) RDS"], correct: 2},
        {question: "EC2 security groups act as?", options: ["A) Virtual firewalls", "B) Load balancers", "C) Storage systems", "D) Databases"], correct: 0},
        {question: "S3 can host?", options: ["A) Static websites", "B) Dynamic websites", "C) Databases", "D) Virtual machines"], correct: 0},
        {question: "Which service is like a retro phone booth - temporary usage?", options: ["A) RDS", "B) S3", "C) Lambda", "D) EC2"], correct: 2},
        {question: "Lambda functions are?", options: ["A) Stateless", "B) Stateful", "C) Both", "D) Neither"], correct: 0},
        {question: "RDS Multi-AZ provides?", options: ["A) High availability", "B) Read replicas", "C) Backup storage", "D) Load balancing"], correct: 0},
        {question: "Which service is like a retro vending machine - serves on demand?", options: ["A) EC2", "B) RDS", "C) Lambda", "D) S3"], correct: 2},
        {question: "EC2 AMI stands for?", options: ["A) Amazon Machine Image", "B) Automatic Machine Instance", "C) Amazon Memory Interface", "D) Advanced Machine Intelligence"], correct: 0},
        {question: "S3 Transfer Acceleration uses?", options: ["A) CloudFront", "B) Direct Connect", "C) VPN", "D) Load Balancers"], correct: 0},
        {question: "Which service is like a retro cash register - counts everything?", options: ["A) Lambda", "B) S3", "C) RDS", "D) EC2"], correct: 1},
        {question: "Lambda layers are used for?", options: ["A) Sharing code", "B) Storage", "C) Networking", "D) Security"], correct: 0},
        {question: "RDS read replicas provide?", options: ["A) Write scaling", "B) Read scaling", "C) Backup only", "D) Security"], correct: 1},
        {question: "Which service is like a retro projector - displays content?", options: ["A) Lambda", "B) RDS", "C) S3", "D) EC2"], correct: 2},
        {question: "EC2 placement groups optimize?", options: ["A) Network performance", "B) Storage performance", "C) Cost", "D) Security"], correct: 0},
        {question: "S3 lifecycle policies can?", options: ["A) Delete objects", "B) Transition storage classes", "C) Both A and B", "D) Neither"], correct: 2},
        {question: "Which service is like a retro alarm clock - triggers at set times?", options: ["A) S3", "B) EC2", "C) Lambda", "D) RDS"], correct: 2},
        {question: "Lambda environment variables are?", options: ["A) Encrypted at rest", "B) Plain text only", "C) Not supported", "D) Temporary only"], correct: 0},
        {question: "RDS parameter groups control?", options: ["A) Database configuration", "B) Network settings", "C) Storage size", "D) Backup frequency"], correct: 0},
        {question: "Which service is like a retro music box - plays when opened?", options: ["A) RDS", "B) EC2", "C) Lambda", "D) S3"], correct: 2},
        {question: "EC2 user data scripts run?", options: ["A) At instance launch", "B) Every hour", "C) On shutdown", "D) Never"], correct: 0},
        {question: "Which service is like a retro game cartridge - plug and play?", options: ["A) RDS", "B) Lambda", "C) S3", "D) EC2"], correct: 1},
        {question: "VPC stands for?", options: ["A) Virtual Private Cloud", "B) Very Private Computing", "C) Virtual Public Cloud", "D) Variable Private Connection"], correct: 0},
        {question: "Which service is like a retro walkie-talkie - sends messages?", options: ["A) S3", "B) SQS", "C) RDS", "D) EC2"], correct: 1},
        {question: "CloudWatch is used for?", options: ["A) Monitoring", "B) Storage", "C) Computing", "D) Networking"], correct: 0},
        {question: "Which service is like a retro bulletin board - posts notifications?", options: ["A) Lambda", "B) SNS", "C) S3", "D) RDS"], correct: 1},
        {question: "IAM stands for?", options: ["A) Internet Access Management", "B) Identity and Access Management", "C) Internal Application Manager", "D) Integrated Account Monitor"], correct: 1},
        {question: "Which service is like a retro security guard - controls access?", options: ["A) S3", "B) Lambda", "C) IAM", "D) EC2"], correct: 2},
        {question: "Route 53 is AWS's?", options: ["A) Storage service", "B) DNS service", "C) Compute service", "D) Database service"], correct: 1},
        {question: "Which service is like a retro phone operator - routes calls?", options: ["A) Route 53", "B) S3", "C) Lambda", "D) RDS"], correct: 0},
        {question: "CloudFront is a?", options: ["A) Database", "B) CDN", "C) Compute service", "D) Storage"], correct: 1},
        {question: "Which service is like a retro newspaper delivery - distributes content?", options: ["A) RDS", "B) CloudFront", "C) Lambda", "D) EC2"], correct: 1},
        {question: "EBS stands for?", options: ["A) Elastic Block Storage", "B) Easy Backup System", "C) Electronic Business Service", "D) Elastic Bandwidth Service"], correct: 0},
        {question: "Which service is like a retro external hard drive?", options: ["A) Lambda", "B) EBS", "C) SNS", "D) SQS"], correct: 1},
        {question: "Auto Scaling automatically?", options: ["A) Backs up data", "B) Adjusts capacity", "C) Routes traffic", "D) Monitors logs"], correct: 1},
        {question: "Which service is like a retro thermostat - adjusts automatically?", options: ["A) Auto Scaling", "B) S3", "C) RDS", "D) Lambda"], correct: 0},
        {question: "Elastic Load Balancer distributes?", options: ["A) Storage", "B) Traffic", "C) Functions", "D) Databases"], correct: 1},
        {question: "Which service is like a retro traffic cop - directs flow?", options: ["A) S3", "B) ELB", "C) Lambda", "D) RDS"], correct: 1},
        {question: "API Gateway manages?", options: ["A) Databases", "B) APIs", "C) Storage", "D) Networks"], correct: 1},
        {question: "Which service is like a retro hotel receptionist - manages requests?", options: ["A) API Gateway", "B) S3", "C) EC2", "D) RDS"], correct: 0},
        {question: "DynamoDB is a?", options: ["A) Relational database", "B) NoSQL database", "C) File system", "D) Cache"], correct: 1},
        {question: "Which service is like a retro card catalog - flexible organization?", options: ["A) RDS", "B) DynamoDB", "C) S3", "D) Lambda"], correct: 1},
        {question: "ElastiCache provides?", options: ["A) Storage", "B) Caching", "C) Computing", "D) Networking"], correct: 1},
        {question: "Which service is like a retro speed dial - quick access?", options: ["A) ElastiCache", "B) S3", "C) EC2", "D) RDS"], correct: 0},
        {question: "Redshift is used for?", options: ["A) Web hosting", "B) Data warehousing", "C) File storage", "D) Function execution"], correct: 1},
        {question: "Which service is like a retro filing warehouse - stores lots of data?", options: ["A) Lambda", "B) Redshift", "C) SNS", "D) SQS"], correct: 1},
        {question: "Kinesis handles?", options: ["A) Static files", "B) Streaming data", "C) Databases", "D) Networks"], correct: 1},
        {question: "Which service is like a retro conveyor belt - continuous flow?", options: ["A) Kinesis", "B) S3", "C) EC2", "D) RDS"], correct: 0},
        {question: "SQS stands for?", options: ["A) Simple Query Service", "B) Simple Queue Service", "C) Secure Queue System", "D) Standard Query Service"], correct: 1},
        {question: "Which service is like a retro post office - queues messages?", options: ["A) SNS", "B) SQS", "C) S3", "D) Lambda"], correct: 1},
        {question: "SNS stands for?", options: ["A) Simple Notification Service", "B) Secure Network Service", "C) Standard Network System", "D) Simple Network Service"], correct: 0},
        {question: "Which service is like a retro town crier - announces news?", options: ["A) SQS", "B) SNS", "C) S3", "D) EC2"], correct: 1},
        {question: "CloudFormation creates?", options: ["A) Databases", "B) Infrastructure as code", "C) Functions", "D) Storage"], correct: 1},
        {question: "Which service is like a retro blueprint - builds from plans?", options: ["A) CloudFormation", "B) S3", "C) Lambda", "D) RDS"], correct: 0},
        {question: "Elastic Beanstalk is for?", options: ["A) Database management", "B) Application deployment", "C) File storage", "D) Network routing"], correct: 1},
        {question: "Which service is like a retro easy-bake oven - simple deployment?", options: ["A) EC2", "B) Elastic Beanstalk", "C) S3", "D) RDS"], correct: 1},
        {question: "CodeCommit is AWS's?", options: ["A) Database", "B) Source control", "C) Monitoring tool", "D) Storage service"], correct: 1},
        {question: "Which service is like a retro filing cabinet for code?", options: ["A) CodeCommit", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "CodeBuild does what?", options: ["A) Stores code", "B) Compiles code", "C) Monitors code", "D) Routes code"], correct: 1},
        {question: "Which service is like a retro assembly line - builds products?", options: ["A) S3", "B) CodeBuild", "C) Lambda", "D) RDS"], correct: 1},
        {question: "CodeDeploy handles?", options: ["A) Code storage", "B) Application deployment", "C) Code compilation", "D) Code monitoring"], correct: 1},
        {question: "Which service is like a retro delivery truck - deploys applications?", options: ["A) CodeDeploy", "B) S3", "C) EC2", "D) Lambda"], correct: 0},
        {question: "X-Ray is used for?", options: ["A) Storage", "B) Application tracing", "C) Computing", "D) Networking"], correct: 1},
        {question: "Which service is like a retro detective - traces problems?", options: ["A) S3", "B) X-Ray", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Systems Manager helps?", options: ["A) Store files", "B) Manage infrastructure", "C) Process data", "D) Route traffic"], correct: 1},
        {question: "Which service is like a retro control panel - manages systems?", options: ["A) Systems Manager", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Secrets Manager stores?", options: ["A) Files", "B) Secrets and passwords", "C) Functions", "D) Databases"], correct: 1},
        {question: "Which service is like a retro safe deposit box - stores secrets?", options: ["A) S3", "B) Secrets Manager", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Parameter Store holds?", options: ["A) Files", "B) Configuration data", "C) Functions", "D) Images"], correct: 1},
        {question: "Which service is like a retro settings notebook - stores config?", options: ["A) Parameter Store", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "CloudTrail records?", options: ["A) Performance metrics", "B) API calls", "C) Error logs", "D) Network traffic"], correct: 1},
        {question: "Which service is like a retro security camera - records activity?", options: ["A) S3", "B) CloudTrail", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Config tracks?", options: ["A) Performance", "B) Resource configuration", "C) Costs", "D) Traffic"], correct: 1},
        {question: "Which service is like a retro inventory clerk - tracks changes?", options: ["A) Config", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "GuardDuty provides?", options: ["A) Storage", "B) Threat detection", "C) Computing", "D) Networking"], correct: 1},
        {question: "Which service is like a retro security alarm - detects threats?", options: ["A) S3", "B) GuardDuty", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Inspector performs?", options: ["A) Data backup", "B) Security assessment", "C) Load balancing", "D) File storage"], correct: 1},
        {question: "Which service is like a retro building inspector - checks security?", options: ["A) Inspector", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Macie discovers?", options: ["A) Performance issues", "B) Sensitive data", "C) Network problems", "D) Cost savings"], correct: 1},
        {question: "Which service is like a retro treasure hunter - finds sensitive data?", options: ["A) S3", "B) Macie", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Shield protects against?", options: ["A) Data loss", "B) DDoS attacks", "C) Cost overruns", "D) Performance issues"], correct: 1},
        {question: "Which service is like a retro fortress wall - blocks attacks?", options: ["A) Shield", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "WAF filters?", options: ["A) Data", "B) Web traffic", "C) Functions", "D) Storage"], correct: 1},
        {question: "Which service is like a retro bouncer - filters web requests?", options: ["A) S3", "B) WAF", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Certificate Manager handles?", options: ["A) User accounts", "B) SSL certificates", "C) File storage", "D) Network routing"], correct: 1},
        {question: "Which service is like a retro locksmith - manages certificates?", options: ["A) Certificate Manager", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "KMS manages?", options: ["A) Files", "B) Encryption keys", "C) Networks", "D) Databases"], correct: 1},
        {question: "Which service is like a retro key master - manages encryption?", options: ["A) S3", "B) KMS", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Cognito handles?", options: ["A) File storage", "B) User authentication", "C) Data processing", "D) Network routing"], correct: 1},
        {question: "Which service is like a retro ID checker - verifies users?", options: ["A) Cognito", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Directory Service provides?", options: ["A) File storage", "B) User directories", "C) Data processing", "D) Network routing"], correct: 1},
        {question: "Which service is like a retro phone book - directory of users?", options: ["A) S3", "B) Directory Service", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Organizations helps?", options: ["A) Store files", "B) Manage multiple accounts", "C) Process data", "D) Route traffic"], correct: 1},
        {question: "Which service is like a retro company organizer - manages accounts?", options: ["A) Organizations", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Cost Explorer shows?", options: ["A) Performance metrics", "B) Cost analysis", "C) Security issues", "D) Network traffic"], correct: 1},
        {question: "Which service is like a retro accountant - tracks spending?", options: ["A) S3", "B) Cost Explorer", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Budgets helps?", options: ["A) Store data", "B) Control costs", "C) Process functions", "D) Route traffic"], correct: 1},
        {question: "Which service is like a retro piggy bank - manages budgets?", options: ["A) Budgets", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Trusted Advisor provides?", options: ["A) File storage", "B) Best practice recommendations", "C) Data processing", "D) Network routing"], correct: 1},
        {question: "Which service is like a retro wise elder - gives advice?", options: ["A) S3", "B) Trusted Advisor", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Support Center offers?", options: ["A) File storage", "B) Technical support", "C) Data processing", "D) Network routing"], correct: 1},
        {question: "Which service is like a retro help desk - provides support?", options: ["A) Support Center", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Personal Health Dashboard shows?", options: ["A) Cost data", "B) Service health", "C) Performance metrics", "D) Security alerts"], correct: 1},
        {question: "Which service is like a retro health monitor - checks service status?", options: ["A) S3", "B) Personal Health Dashboard", "C) Lambda", "D) RDS"], correct: 1},
        {question: "Well-Architected Tool helps?", options: ["A) Store files", "B) Review architecture", "C) Process data", "D) Route traffic"], correct: 1},
        {question: "Which service is like a retro architect's ruler - measures design?", options: ["A) Well-Architected Tool", "B) S3", "C) Lambda", "D) EC2"], correct: 0},
        {question: "Service Health Dashboard displays?", options: ["A) Personal alerts", "B) Global service status", "C) Cost information", "D) Performance data"], correct: 1},
        {question: "Which service is like a retro town bulletin - shows public status?", options: ["A) S3", "B) Service Health Dashboard", "C) Lambda", "D) RDS"], correct: 1}
    ];

    static getRandomQuestion() {
        return this.questions[Math.floor(Math.random() * this.questions.length)];
    }
}